/**
 * 全局配置文件
 */
export default {
  title: 'saber',
  logo: '/img/logo.png',
  key: 'saber',
  indexTitle: 'BIP2.0',
  clientId: 'saber3',
  clientSecret: 'saber3_secret',
  tenantMode: true,
  tenantId: '000000',
  captchaMode: false,
  switchMode: false,
  tokenTime: 3000,
  tokenHeader: 'Blade-Auth',
  statusWhiteList: [],
  setting: {
    sidebar: 'vertical',
    tag: true,
    collapse: true,
    search: true,
    lock: true,
    screenshot: true,
    fullscreen: true,
    theme: true,
    menu: true,
  },
  fistPage: {
    name: '工作台',
    path: '/desk/index',
  },
  menu: {
    iconDefault: 'icon-caidan',
    label: 'name',
    path: 'path',
    icon: 'source',
    children: 'children',
    query: 'query',
    href: 'path',
    meta: 'meta',
    displayType: 'displayType',
  },
  oauth2: {
    registerMode: true,
    publicKey:
      '04371300310e53c6bcce15b1b5b6b5429a30211f8cb023d97a7eeda289475cb5d024026f255affacabd06ff215287427b231643e30b0fa88c1673cebcbd91a2a1e',
    authUrl: `${import.meta.env.VITE_APP_BASE_URL}/blade-auth/oauth/render`,
    ssoUrl: `${import.meta.env.VITE_APP_BASE_URL}/oauth/authorize?client_id=saber3&response_type=code&redirect_uri=`,
    redirectUri: `${import.meta.env.VITE_APP_BASE_URL}/login`,
  },
  design: {
    designMode: true,
    designUrl: `${import.meta.env.VITE_APP_DESIGN_URL}`,
    reportUrl: `${import.meta.env.VITE_APP_REPORT_URL}`,
  },
  urlTokenWhiteList: [
    '/',
    '/login',
    '/process-priview',
    '/dashboard/projectSchedule',
    '/dashboard/commandRoom/index',
    '/dashboard/onSitePlan',
    '/dashboard/assemblyboard',
    '/dashboard/humanResources/index',
    '/desk/webviewNfdesign',
    '/dashboard/floorboard/index',
  ],
};
